require("moiamond.plugins-setup")
require("moiamond.core.options")
require("moiamond.core.keymaps")
require("moiamond.core.colorscheme")
require("moiamond.plugins-setup")
require("moiamond.core.options")
require("moiamond.core.keymaps")
require("moiamond.core.colorscheme")
require("moiamond.plugins.comment")
require("moiamond.plugins.nvim-tree")
require("moiamond.plugins.lualine")
require("moiamond.plugins.nvim-cmp")
require("moiamond.plugins.autopairs")
require("moiamond.plugins.gitsigns")

-- require("moiamond.plugins.telescope")
-- require("moiamond.plugins.lsp.mason")
-- require("moiamond.plugins.lsp.lspsaga")
-- require("moiamond.plugins.lsp.lspconfig")
-- require("moiamond.plugins.lsp.null-ls")
-- require("moiamond.plugins.treesitter")